spring:
  kafka:
    consumer:
      group-id: proc1
      client-id: c1
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            partition:
              assignment:
                strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
      bindings:
        input:
          group: proc1
          contentType: application/*+avro
          destination: proc12-topic
          consumer:
            headerMode: raw
      schemaRegistryClient:
        endpoint: http://localhost:8081
      schema:
        avro:
          schema-locations: classpath:avro/proc1.avsc
producer:
  url: localhost:9011
